# Site settings
title: Saçmalardan Seçmeler
email: umt.toker@gmail.com
description: Blog yazmak için çok artı özellikleri olmayan muhtemelen bundan 10-15 sene sonra kel göbekli bir mühendis olacak sırandan bir vatandaşım efendim.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://umuttoker.com" # the base hostname & protocol for your site
twitter_username: umuttoker
github_username:  umuttoker

# Build settings
markdown: kramdown
